export const DECK_SELECT = "DECK_SELECT";
export const DECK_CHANGE = "DECK_CHANGE";
export const DECK_CREATE = "DECK_CREATE";
export const DECKS_FETCH = "DECKS_FETCH";
export const DECKS_FETCH_SUCCESS = "DECKS_FETCH_SUCCESS";

export const QUESTION_CHANGE = "QUESTION_CHANGE";
export const QUESTION_CREATE = "QUESTION_CREATE";

export const ANSWER_SORT = "ANSWER_SORT";
export const QUIZ_RESET = "QUIZ_RESET";
